[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "img-src 'self' http://defi24.mathis-guellati.fr:8091 data: https:; default-src 'self' http://defi24.mathis-guellati.fr:8091 https:; connect-src 'self' http://defi24.mathis-guellati.fr:8091 https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
